apiVersion: v2
name: streama
version: 1.0.0
kubeVersion: ">=1.22.0"
description: Self-hosted streaming media server
type: application
keywords:
  - streaming
  - video
home: https://docs.streama-project.com/
sources:
  - https://github.com/streamaserver/streama
  - https://github.com/just1not2/helm-chart-streama
dependencies:
  - name: mysql
    version: ^8.8.26
    repository: https://charts.bitnami.com/bitnami
    condition: mysql.enabled
maintainers:
  - name: Justin Béra
    email: me@just1not2.org
icon: https://raw.githubusercontent.com/streamaserver/streama/master/design/logo_new.png
appVersion: "1.10.4"
deprecated: false
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/images: |
    - name: streama
      image: just1not2/streama:1.10.4
  artifacthub.io/changes: |
    - kind: added
      description: Initial release
